name: Fly Deploy
on:
  push:
    branches:
      - "master"
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    concurrency:
      group: ci-studio-${{ github.ref }}
      cancel-in-progress: true

    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy"
